---
title: "IREX flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    runtime: shiny
    orientation: rows
    social: menu
    source: embed
--- 

```{r global, include=FALSE} 
knitr::opts_chunk$set(cache = TRUE)
library(dplyr)
library(viridisLite)
library(ggplot2)
library(plotly)
library(tidyverse)
library(rgdal)
library(sp)
library(leaflet)
library(magrittr)
library(maptools)
library(rgeos)
library(RColorBrewer)
library(maptools)
library(devtools)
library(flexdashboard)
library(shiny)
library(DT)

##read in project data
maptest<-read.csv("maptest.csv",header=TRUE)
dashtest<-read.csv("sfTest.csv",header=TRUE)

list<-c("program", "country","FY","period","indicator number","disaggregation","disaggregation value","timing","noData","results","practice area")
names(dashtest)<-list 

##what was the below code supposed to do? it was preventing the disaggregations from being displayed properly
#dashtest2<-dashtest %>% filter(disaggregation=="a. Country") %>% .[,c(1,2,3,4,5,10,11)]
dashtest2 <- dashtest

```




Page 1 : Overall Country Results Per Indicator {data-icon="fa-list"}
===================================== 

Column {.sidebar}
-------------------------------------
### Inputs

```{r}
selectInput("practice_area", label="Practice Area", choices=unique(dashtest2$`practice area`))

selectInput("indicator_number", label="Indicator Number", choices=sort(unique(dashtest2$`indicator number`)))

selectInput("country", label="Country", choices=unique(dashtest2$country)) 


```

Row
------------------------------------- 


### Value Boxes 



### Histogram
```{r cache=FALSE}

renderPlot({ 
  histogramDataset = subset(dashtest2, `practice area`==input$practice_area) 
  histogramDataset = subset(histogramDataset,country==input$country) 
  histogramDataset = subset(histogramDataset, `indicator number`==input$indicator_number)

  ggplot(histogramDataset,aes(x=results)) + geom_histogram()

})
```


Row {.tabset}
------------------------------------- 

### Map

### Table Chart 4  

```{r cache=FALSE}
DT::renderDataTable({ 
  #countrySelected = as.character(input$country) 
selectedDataset = subset(dashtest2, `practice area`==input$practice_area) 
selectedDataset = subset(selectedDataset,country==input$country) 
selectedDataset = subset(selectedDataset, `indicator number`==input$indicator_number)
selectedDataset = subset(selectedDataset, select = c(program,country,results))
  DT::datatable(selectedDataset, options = list(
    pageLength = 10
  ))
})
```

Page 2 : Deep Dive into disaggregation {data-icon="fa-map"}
===================================== 

Column {.sidebar}
-------------------------------------
### Inputs

```{r cache=FALSE}

selectInput("indicator_number", label="Indicator Number", choices=sort(unique(dashtest2$`indicator number`)))

selectInput("disaggregation", label="Disaggregation", choices=sort(unique(dashtest2$disaggregation))) 

#The below block of code is still under testing
#testing whether there is a better way to select the disaggregation values
#dataset_disaggregation = subset(dashtest2,disaggregation==input.disaggregation)
#vector_choice = sort(unique(dataset_disaggregation$`disaggregation value`)) 


# Only show this panel if a specific disaggregation type is selected
  conditionalPanel(
       condition = "input.disaggregation == 'b. Gender'",
       selectInput("disaggregation_type", label="Gender",c("Male","Female")))  
   
   conditionalPanel(
       condition = "input.disaggregation == 'a. Country'",
       selectInput("disaggregation_type", label="Country", c("Overall")))   
   
   conditionalPanel(
       condition = "input.disaggregation == 'c. Youth/Adult'",
       selectInput("disaggregation_type", label="Youth/Adult", c("a. Youth","b. Adult"))) 
   
     conditionalPanel(
       condition = "input.disaggregation == 'd. Age Range'",
       selectInput("disaggregation_type", label="Age Range", c("a. Adolescence (10-14)","b. Late adolescence (15-19)","c. Young adulthood (20-24)","d. Transition to adulthood (25-29)")))  
     
     conditionalPanel(
       condition = "input.disaggregation == 'e. Underserved Group'",
       selectInput("disaggregation_type", label="Undeserved Group", c("a. underserved due to sexual orientation","b. Persons with disabilities","c. Low economic status ","d. Racial/ethnic/religious group","e. Other","Overall                                 ")))  
     
      conditionalPanel(
       condition = "input.disaggregation == 'f. Location'",
       selectInput("disaggregation_type", label="Location", c("Rural","Semi-urban","Urban")))  
      
      conditionalPanel(
       condition = "input.disaggregation == 'g. Type of Education/Employment Status Change'",
       selectInput("disaggregation_type", label="Type of Education/Employment Status", c("From unemployment to part-time/informal employment","Received promotion to more senior position and/or salary increase","Started own business or enterprise")))   
      
       conditionalPanel(
       condition = "input.disaggregation == 'h. Intensity of Intervention'",
       selectInput("disaggregation_type", label="Intensity of Intervention", c("a. Short-term","b. Medium-term","c. Long-term ")))   
       
       conditionalPanel(
       condition = "input.disaggregation == 'i. Number Employers Engaged in Following Ways'",selectInput("disaggregation_type", label="Number Employers Engaged in Following Ways", c("Contributing to educational content/curricula","Internships/apprenticeships")))   
       
       conditionalPanel(
       condition = "input.disaggregation == 'j. Employer Type'",selectInput("disaggregation_type", label="Employer Type", c("Civil society/media Government","Other", "Private sector"))) 
       
        conditionalPanel(
       condition = "input.disaggregation == 'k. Leader Type'",selectInput("disaggregation_type", label="Leader Type", c("CSO","Educator", "HEI/Career center Library ","Media","Other"))) 
        
        conditionalPanel(
       condition = "input.disaggregation == 'l. Collaboration Type'",selectInput("disaggregation_type", label="Collaboration Type", c("Between education institutions Between libraries","CSO to CSO", " Media to media outlet ","Other"))) 
        
        conditionalPanel(
       condition = "input.disaggregation == 'm. Institution Type'",selectInput("disaggregation_type", label="Institution Type", c("CSO","Government agency/institution", "HEI/Community college/Career center","Library","Non-state news outlet","Other","Primary/secondary school"))) 
        
         conditionalPanel(
       condition = "input.disaggregation == 'Media Type'",selectInput("disaggregation_type", label="Media Type", c("Online Radio","TV"))) 
         
         conditionalPanel(
       condition = "input.disaggregation == 'n. Media Partner Type'",selectInput("disaggregation_type", label="Media Partner Type", c("Citizen Journalist","Mixed Media Outlet","Print Media Outlet","Radio Outlet","TV Outlet"))) 
         
         conditionalPanel(
       condition = "input.disaggregation == 'o. Educator Institution Type'",selectInput("disaggregation_type", label="Educator Institution Type", c("Primary/secondary school")))
 
          conditionalPanel(
       condition = "input.disaggregation == 'p. Employer engaged by IREX/partner'",selectInput("disaggregation_type", label="Engaged By", c("a.  IREX","b. IREX partner"))) 
#selectInput("disaggregation_category",label="Disaggregation #Value",choices=vector_choice) 
          
          selectInput("program", label="Program", choices=sort(unique(dashtest2$program))) 

```

Row
------------------------------------- 

### Statistics

### Bubble Chart

Row
------------------------------------- 

### Table 
```{r cache=FALSE}
DT::renderDataTable({ 
selectedDataset2 = subset(dashtest2, `indicator number`==input$indicator_number) 
selectedDataset2 = subset(selectedDataset2,disaggregation==input$disaggregation) 
selectedDataset2 = subset(selectedDataset2, `disaggregation value`==input$disaggregation_type) 
selectedDataset2 = subset(selectedDataset2, program==input$program)
selectedDataset2 = subset(selectedDataset2, select = c(program,disaggregation,`disaggregation value`,results))
  DT::datatable(selectedDataset2, options = list(
    pageLength = 10
  ))
})
```
